### Login User
### This step is always necessary
### Normally every endpoint would check:
### 1.- x-api-key = Should be the same as defined API_KEY in .env
### 2.- Authorization = This token is returned when auth/login is called successfully
### 3.- Depending on the endpoint validations on user roles [user_entity.roles] will be done 
### Note: Authorization error would return 'Invalid Authorization', this is how the FE knows
### should request user to login again
# @name login
curl --location --request GET '{{base_url}}/user/auth/login' \
--header 'Content-Type: application/json' \
--header 'x-api-key: {{apiKey}}' \
--header 'username: root' \
--header 'password: {{gigabyte_root_password}}' \
@BearerToken = '{{login.response.body.$.accessToken}}'
@UserId = '{{login.response.body.$.id}}'
 
### Event Definition Get All
curl --location --request GET '{{base_url}}/event/definition' \
--header 'Content-Type: application/json' \
--header 'x-api-key: {{apiKey}}' \
--header 'Authorization: Bearer {{BearerToken}}' \

### Event Definition Get All with search params
curl --location --request GET '{{base_url}}/event/definition?param=' \
--header 'Content-Type: application/json' \
--header 'x-api-key: {{apiKey}}' \
--header 'Authorization: Bearer {{BearerToken}}' \

### Event Definition Create New
# @name eventDef
curl --location --request POST '{{base_url}}/event/definition' \
--header 'Content-Type: application/json' \
--header 'x-api-key: {{apiKey}}' \
--header 'Authorization: Bearer {{BearerToken}}' \
--data-raw '{
    "code": "CODE{{$randomInt 0 9999}}",
    "source": "ContactID",
    "description": "Description {{$randomInt 0 9999}}",
    "dataType": "Type{{$randomInt 0 9999}}",
    "codeType": "Code{{$randomInt 0 9999}}",
    "level": "#006666",
    "type": "AUTOTEST",
    "delayMin": 0,
    "activationFlag": false
}'
@EventDefId = '{{eventDef.response.body.$.id}}'

### Event Definition Get One
curl --location --request GET '{{base_url}}/event/definition' \
--header 'Content-Type: application/json' \
--header 'x-api-key: {{apiKey}}' \
--header 'Authorization: Bearer {{BearerToken}}' \
--header 'x-resource-id: {{EventDefId}}' \

### Event Definition created Client
curl --location --request PUT '{{base_url}}/event/definition' \
--header 'Content-Type: application/json' \
--header 'x-api-key: {{apiKey}}' \
--header 'Authorization: Bearer {{BearerToken}}' \
--data-raw '{
    "id": "{{EventDefId}}",
    "code": "CODE{{$randomInt 0 9999}}",
    "source": "ContactID",
    "description": "Description {{$randomInt 0 9999}}",
    "dataType": "Type{{$randomInt 0 9999}}",
    "codeType": "Code{{$randomInt 0 9999}}",
    "level": "#006666",
    "type": "AUTOTEST",
    "delayMin": 0,
    "activationFlag": false
}'
   
### Event Definition created Client
curl --location --request DELETE '{{base_url}}/event/definition' \
--header 'Content-Type: application/json' \
--header 'x-api-key: {{apiKey}}' \
--header 'x-resource-id: {{EventDefId}}' \
--header 'Authorization: Bearer {{BearerToken}}'